"""Compile the TikZ figures in figures/ into one committed TypeScript module.

    python tools/build_figures.py           # rebuild (needs a TeX Live with dvisvgm)
    python tools/build_figures.py --check   # CI: sources and generated file agree

Why a generated module and not a .svg under public/: the drawings are line art,
and inlining them lets every stroke be `currentColor`, so one figure follows the
dark theme, the light theme and the printed sheet without a second version.

`--check` deliberately needs **no LaTeX**. Each figure records the sha256 of the
.tex it came from, so CI can catch a source edited without a rebuild while only
the author's machine needs the toolchain.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIGURES_DIR = ROOT / "figures"
OUT = ROOT / "web" / "src" / "content" / "figures.generated.ts"

HEADER = """\
// GENERATED by tools/build_figures.py — do not edit.
// Sources: figures/<name>.tex. Rebuild with `python tools/build_figures.py`.
//
// Each drawing is inline SVG with `currentColor` strokes, so it follows the
// site's theme and prints black. Interpolate one into a statement with
// `${figure("abacus/tiles-in-a-box")}`, on its own blank-line-separated
// paragraph so markdown treats it as a block.

export interface Figure {
  svg: string;
  /** sha256 of the .tex it was built from — see tools/build_figures.py --check. */
  source: string;
}

"""

FOOTER = """
export function figure(name: keyof typeof FIGURES): string {
  return FIGURES[name].svg;
}
"""


def sources() -> list[Path]:
    return sorted(FIGURES_DIR.rglob("*.tex"))


def name_of(tex: Path) -> str:
    return tex.relative_to(FIGURES_DIR).with_suffix("").as_posix()


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def compile_svg(tex: Path) -> str:
    """latex → dvi → svg, then make the result themeable."""
    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp)
        shutil.copy(tex, work / tex.name)
        run = subprocess.run(
            ["latex", "-interaction=nonstopmode", "-halt-on-error", tex.name],
            cwd=work,
            capture_output=True,
            text=True,
        )
        if run.returncode != 0:
            raise SystemExit(f"latex failed on {tex}:\n{run.stdout[-2000:]}")
        dvi = work / (tex.stem + ".dvi")
        svg = work / (tex.stem + ".svg")
        run = subprocess.run(
            ["dvisvgm", "--no-fonts", "--exact", "--bbox=min", "-o", svg.name, dvi.name],
            cwd=work,
            capture_output=True,
            text=True,
        )
        if run.returncode != 0:
            raise SystemExit(f"dvisvgm failed on {tex}:\n{run.stderr[-2000:]}")
        return clean(svg.read_text(encoding="utf8"))


def clean(svg: str) -> str:
    # Drop the XML prologue and the generator comment: this goes inside a page,
    # not into a file of its own.
    svg = re.sub(r"<\?xml[^>]*\?>\s*", "", svg)
    svg = re.sub(r"<!--.*?-->\s*", "", svg, flags=re.S)

    # Black is the only colour the sources use, and it becomes the reader's text
    # colour — the whole reason these are inlined rather than served as files.
    svg = svg.replace("'#000'", "'currentColor'").replace('"#000"', '"currentColor"')

    # Decorative: the statement says in words what the picture shows.
    svg = svg.replace(
        "<svg ", '<svg class="tikz-figure" role="presentation" aria-hidden="true" ', 1
    )
    return svg.strip()


def render(figures: dict[str, dict[str, str]]) -> str:
    body = ",\n".join(
        f"  {json.dumps(name)}: {{\n"
        f"    source: {json.dumps(f['source'])},\n"
        f"    svg: {json.dumps(f['svg'])},\n"
        f"  }}"
        for name, f in figures.items()
    )
    return f"{HEADER}export const FIGURES = {{\n{body},\n}} satisfies Record<string, Figure>;\n{FOOTER}"


def committed() -> dict[str, str]:
    """name → recorded source hash, read out of the generated module."""
    if not OUT.exists():
        return {}
    text = OUT.read_text(encoding="utf8")
    return dict(re.findall(r'^  "([^"]+)": \{\n    source: "([0-9a-f]{64})",', text, re.M))


def check() -> int:
    recorded = committed()
    expected = {name_of(t): sha(t) for t in sources()}
    problems = []
    for name, digest in expected.items():
        if name not in recorded:
            problems.append(f"  {name}: never built")
        elif recorded[name] != digest:
            problems.append(f"  {name}: .tex changed since the last build")
    for name in recorded.keys() - expected.keys():
        problems.append(f"  {name}: built from a .tex that no longer exists")
    if problems:
        print("figures.generated.ts is out of date:", *problems, sep="\n")
        print("\nRun: python tools/build_figures.py")
        return 1
    print(f"Figures are up to date ({len(expected)} drawings).")
    return 0


def build() -> int:
    figures = {}
    for tex in sources():
        name = name_of(tex)
        print(f"  {name}")
        figures[name] = {"source": sha(tex), "svg": compile_svg(tex)}
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(figures), encoding="utf8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(figures)} drawings).")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify without LaTeX")
    args = parser.parse_args()
    return check() if args.check else build()


if __name__ == "__main__":
    sys.exit(main())
